# Stage 1: Build React
FROM node:18-alpine as builder

WORKDIR /app

COPY frontend/package*.json ./   
RUN npm install

COPY frontend/. ./ 

RUN npm run build

# Stage 2: Serve with nginx
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]