#version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: hackernews-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react-nginx
    ports:
      - "80:80"
    restart: unless-stopped

  go-server:
    build:
      context: .
      dockerfile: Dockerfile.golang
    container_name: go-server
    restart: unless-stopped
    ports:
      - "30000:30000"
    env_file:
      - ./.env
    depends_on:
      - postgres
